name: CICD_for_dev_srv
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Reset Permissions before deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.NAME }}
          key: ${{ secrets.KEY }}
          #passphrase:  ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            sudo chmod -R 775 /var/www/html/cicdtesting
            sudo chown -R root:root /var/www/html/cicdtesting
            
      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.NAME }}
          PORT: 22
          KEY: ${{ secrets.KEY }}
          #passphrase:  ${{ secrets.PASSPHRASE }}
        with:
          source: "*"
          target: "/var/www/html/cicdtesting"

      - name: Reset Permissions after deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.NAME }}
          key: ${{ secrets.KEY }}
          #passphrase:  ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            sudo chmod -R 755 /var/www/html/cicdtesting
            sudo chown -R apache:apache /var/www/html/cicdtesting
